server:
  port: 8080
  error:
    path: /errorsup

spring:
  datasource:
    url: jdbc:postgresql://db.jezgxwgyhoahidqbtyia.supabase.co:5432/postgres
    username: postgres
    password: UAKUVdMeKV2Rxiv0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto:  update
    show-sql: false

  devtools:
    livereload:
      enabled: true
